System.register("chunks:///_virtual/CameraComponent.ts",["./rollupPluginModLoBabelHelpers.js","cc","./GameEvent.ts"],(function(t){"use strict";var i,o,e,r,n,s,a,c,p,u;return{setters:[function(t){i=t.applyDecoratedDescriptor,o=t.inheritsLoose,e=t.initializerDefineProperty,r=t.assertThisInitialized},function(t){n=t.cclegacy,s=t._decorator,a=t.Node,c=t.Vec3,p=t.Component},function(t){u=t.GameEvent}],execute:function(){var l,h,C,v,f;n._RF.push({},"43ac8zi+5pC777qPjNTSr4o","CameraComponent",void 0);var g=s.ccclass,m=s.property;t("CameraComponent",(l=g("CameraComponent"),h=m(a),l((f=i((v=function(t){function i(){for(var i,o=arguments.length,n=new Array(o),s=0;s<o;s++)n[s]=arguments[s];return i=t.call.apply(t,[this].concat(n))||this,e(i,"target",f,r(i)),i.previousTargetPosition=void 0,i.isCrash=!1,i}o(i,t);var n=i.prototype;return n.start=function(){this.previousTargetPosition=this.target.position.clone(),u.on("CRASH",this.onCrash,this)},n.update=function(t){if(!this.isCrash){var i=this.node.worldPosition,o=i.x,e=i.y,r=i.z,n=this.target.position.x-this.previousTargetPosition.x,s=new c(o+n,e,r);this.node.worldPosition=s,this.previousTargetPosition=this.target.position.clone()}},n.onCrash=function(){this.isCrash=!0},i}(p)).prototype,"target",[h],{configurable:!0,enumerable:!0,writable:!0,initializer:null}),C=v))||C));n._RF.pop()}}}));

System.register("chunks:///_virtual/CoinComponent.ts",["./rollupPluginModLoBabelHelpers.js","cc"],(function(t){"use strict";var e,o,n,i,r,s,a,c,p;return{setters:[function(t){e=t.applyDecoratedDescriptor,o=t.inheritsLoose,n=t.initializerDefineProperty,i=t.assertThisInitialized},function(t){r=t.cclegacy,s=t._decorator,a=t.CCFloat,c=t.Vec3,p=t.Component}],execute:function(){var u,l,h,f,d;r._RF.push({},"23ce1XMzoJJUbKs/RT8vKUD","CoinComponent",void 0);var C=s.ccclass,y=s.property;t("CoinComponent",(u=C("CoinComponent"),l=y(a),u((d=e((f=function(t){function e(){for(var e,o=arguments.length,r=new Array(o),s=0;s<o;s++)r[s]=arguments[s];return e=t.call.apply(t,[this].concat(r))||this,n(e,"speed",d,i(e)),e.startRotation=new c,e}o(e,t);var r=e.prototype;return r.start=function(){this.startRotation=new c,this.node.rotation.getEulerAngles(this.startRotation)},r.update=function(t){this.startRotation.y+=this.speed,this.node.setRotationFromEuler(this.startRotation)},e}(p)).prototype,"speed",[l],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return 8}}),h=f))||h));r._RF.pop()}}}));

System.register("chunks:///_virtual/DownloadComponent.ts",["./rollupPluginModLoBabelHelpers.js","cc","./GameEvent.ts","./URL.ts"],(function(e){"use strict";var t,n,o,i,r,a,c,p,s,l,u,d,h;return{setters:[function(e){t=e.applyDecoratedDescriptor,n=e.inheritsLoose,o=e.initializerDefineProperty,i=e.assertThisInitialized},function(e){r=e.cclegacy,a=e._decorator,c=e.UIOpacity,p=e.CCFloat,s=e.tween,l=e.sys,u=e.Component},function(e){d=e.GameEvent},function(e){h=e.URL}],execute:function(){var y,f,m,v,C,b,w,D;r._RF.push({},"6ab233X1vFDhrFdFbuZOHQz","DownloadComponent",void 0);var g=a.ccclass,F=a.property,R=a.requireComponent;e("DownloadComponent",(y=g("DownloadComponent"),f=R(c),m=F(p),v=F(p),y(C=f((w=t((b=function(e){function t(){for(var t,n=arguments.length,r=new Array(n),a=0;a<n;a++)r[a]=arguments[a];return t=e.call.apply(e,[this].concat(r))||this,o(t,"delay",w,i(t)),o(t,"hideSpeed",D,i(t)),t.opacity=void 0,t}n(t,e);var r=t.prototype;return r.start=function(){this.opacity=this.node.getComponent(c),d.on("CRASH",this.hide,this)},r.hide=function(){var e=this;this.scheduleOnce((function(){s(e.opacity).to(e.hideSpeed,{opacity:1}).start()}),this.delay)},r.onDownload=function(){l.openURL(h.url)},t}(u)).prototype,"delay",[m],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return 1}}),D=t(b.prototype,"hideSpeed",[v],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return.5}}),C=b))||C)||C));r._RF.pop()}}}));

System.register("chunks:///_virtual/FailWindowComponent.ts",["./rollupPluginModLoBabelHelpers.js","cc","./GameEvent.ts","./URL.ts"],(function(e){"use strict";var t,r,o,i,n,s,a,c,l,p,u,y,d,h,f;return{setters:[function(e){t=e.applyDecoratedDescriptor,r=e.inheritsLoose,o=e.initializerDefineProperty,i=e.assertThisInitialized},function(e){n=e.cclegacy,s=e._decorator,a=e.UIOpacity,c=e.CCFloat,l=e.Vec3,p=e.tween,u=e.Quat,y=e.sys,d=e.Component},function(e){h=e.GameEvent},function(e){f=e.URL}],execute:function(){var b,C,w,m,v,g,O,S,R,z,B,F,E,L,D,W,H;n._RF.push({},"70a50C18/tHWL4YgLKcDpfb","FailWindowComponent",void 0);var U=s.ccclass,_=s.property;e("FailWindowComponent",(b=U("FailWindowComponent"),C=_(a),w=_(c),m=_(c),v=_(c),g=_(a),O=_(c),S=_(c),b((B=t((z=function(e){function t(){for(var t,r=arguments.length,n=new Array(r),s=0;s<r;s++)n[s]=arguments[s];return t=e.call.apply(e,[this].concat(n))||this,o(t,"cross",B,i(t)),o(t,"speedCrossRotation",F,i(t)),o(t,"speedCrossScale",E,i(t)),o(t,"speedCrossOpacity",L,i(t)),o(t,"retryButton",D,i(t)),o(t,"speedretryScale",W,i(t)),o(t,"speedretryOpacity",H,i(t)),t.bigScale=new l(1.2,1.2,1.2),t}r(t,e);var n=t.prototype;return n.start=function(){this.cross.opacity=1,this.cross.node.scale=l.ZERO,this.node.active=!1,h.on("CRASH",this.showCross,this),h.on("CRASH",this.showTryButton,this)},n.showCross=function(){var e=this,t=p(this.cross).to(1/this.speedCrossOpacity,{opacity:255}),r=new u;u.fromEuler(r,0,0,179);var o=p(this.cross.node).to(1/this.speedCrossRotation,{rotation:r}),i=p(this.cross.node).to(1/this.speedCrossScale,{scale:l.ONE});this.scheduleOnce((function(){e.node.active=!0,t.start(),p(e.cross.node).parallel(o,i).start()}),2)},n.showTryButton=function(){var e=this,t=p(this.retryButton).to(1/this.speedretryOpacity,{opacity:255}),r=p(this.retryButton.node).to(this.speedretryScale,{scale:this.bigScale}).to(this.speedretryScale,{scale:l.ONE}).delay(2),o=p(this.retryButton.node).to(1/this.speedretryScale,{scale:l.ONE}).call((function(){p(e.retryButton.node).repeatForever(r).start()}));this.scheduleOnce((function(){t.start(),o.start()}),2)},n.onDownload=function(){y.openURL(f.url)},t}(d)).prototype,"cross",[C],{configurable:!0,enumerable:!0,writable:!0,initializer:null}),F=t(z.prototype,"speedCrossRotation",[w],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return 1}}),E=t(z.prototype,"speedCrossScale",[m],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return 1}}),L=t(z.prototype,"speedCrossOpacity",[v],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return 1}}),D=t(z.prototype,"retryButton",[g],{configurable:!0,enumerable:!0,writable:!0,initializer:null}),W=t(z.prototype,"speedretryScale",[O],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return 1}}),H=t(z.prototype,"speedretryOpacity",[S],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return 1}}),R=z))||R));n._RF.pop()}}}));

System.register("chunks:///_virtual/FanComponent.ts",["./rollupPluginModLoBabelHelpers.js","cc"],(function(t){"use strict";var e,n,o,r,i,a,s,c,l;return{setters:[function(t){e=t.applyDecoratedDescriptor,n=t.inheritsLoose,o=t.initializerDefineProperty,r=t.assertThisInitialized},function(t){i=t.cclegacy,a=t._decorator,s=t.Node,c=t.Vec3,l=t.Component}],execute:function(){var p,u,h,f,y;i._RF.push({},"c5f32IH3ZRCnJLY9Yf3lzNM","FanComponent",void 0);var R=a.ccclass,d=a.property;t("FanComponent",(p=R("FanComponent"),u=d(s),p((y=e((f=function(t){function e(){for(var e,n=arguments.length,i=new Array(n),a=0;a<n;a++)i[a]=arguments[a];return e=t.call.apply(t,[this].concat(i))||this,o(e,"particle",y,r(e)),e.startRotation=new c,e}n(e,t);var i=e.prototype;return i.start=function(){this.startRotation=new c,this.node.rotation.getEulerAngles(this.startRotation)},i.rotate=function(t){this.particle.active=!(0==t),this.startRotation.x+=9*t,this.node.setRotationFromEuler(this.startRotation)},e}(l)).prototype,"particle",[u],{configurable:!0,enumerable:!0,writable:!0,initializer:null}),h=f))||h));i._RF.pop()}}}));

System.register("chunks:///_virtual/GameEvent.ts",["cc"],(function(e){"use strict";var t,n,c;return{setters:[function(e){t=e.cclegacy,n=e._decorator,c=e.EventTarget}],execute:function(){var i,o;t._RF.push({},"3a7dcFli31FJZxE9EjK4IuH","GameEvent",void 0);var u=n.ccclass;e("GameEvent",u("GameEvent")(((o=function(){function e(){}return e.on=function(e,t,n,c){this._event.on(e,t,n,c)},e.once=function(e,t,n){this._event.once(e,t,n)},e.off=function(e,t,n){this._event.off(e,t,n)},e.emit=function(e,t,n){this._event.emit(e,t,n)},e}())._event=new c,i=o))||i);t._RF.pop()}}}));

System.register("chunks:///_virtual/GameEventName.ts",["cc"],(function(e){"use strict";var t;return{setters:[function(e){t=e.cclegacy}],execute:function(){var c;e("GameEventName",void 0),t._RF.push({},"471cf9N1ApIt6Vqocm0eHKO","GameEventName",void 0),function(e){e[e.CRASH=0]="CRASH",e[e.COIN_COLLECT=1]="COIN_COLLECT",e[e.GAME_OVER=2]="GAME_OVER"}(c||(c=e("GameEventName",{}))),t._RF.pop()}}}));

System.register("chunks:///_virtual/HandleComponent.ts",["./rollupPluginModLoBabelHelpers.js","cc"],(function(t){"use strict";var i,e,n,o,a,r,s,l,h,u,d,c,p,m,f;return{setters:[function(t){i=t.applyDecoratedDescriptor,e=t.inheritsLoose,n=t.initializerDefineProperty,o=t.assertThisInitialized,a=t.createClass},function(t){r=t.cclegacy,s=t._decorator,l=t.CCFloat,h=t.Node,u=t.Animation,d=t.UITransform,c=t.Vec3,p=t.tween,m=t.math,f=t.Component}],execute:function(){var v,y,C,_,T,H,b,w,P,g,z,A,E;r._RF.push({},"0d4251JnlNKJZO4rLPhFF1y","HandleComponent",void 0);var S=s.ccclass,k=s.property;t("HandleComponent",(v=S("HandleComponent"),y=k(l),C=k(l),_=k(h),T=k(u),H=k(d),v((P=i((w=function(t){function i(){for(var i,e=arguments.length,a=new Array(e),r=0;r<e;r++)a[r]=arguments[r];return i=t.call.apply(t,[this].concat(a))||this,n(i,"minY",P,o(i)),n(i,"maxY",g,o(i)),n(i,"handle",z,o(i)),n(i,"tutorHandAnimation",A,o(i)),n(i,"hadleTransform",E,o(i)),i._isTutorHandleComplete=!1,i._previousPosition=new c,i._handleSpeed=0,i._diapazon=void 0,i}e(i,t);var r=i.prototype;return r.start=function(){if(!this.handle)throw"handle is null";this._diapazon=this.maxY-this.minY,this._previousPosition=this.handle.worldPosition.clone(),this.handle.on(h.EventType.TOUCH_START,this.mouseClickStart,this),this.handle.on(h.EventType.TOUCH_MOVE,this.mouseClickMove,this),this.handle.on(h.EventType.TOUCH_END,this.mouseClickEnd,this),this.handle.on(h.EventType.TOUCH_CANCEL,this.mouseClickEnd,this)},r.mouseClickStart=function(t){var i=this;this._isTutorHandleComplete||(this._isTutorHandleComplete=!0,this.tutorHandAnimation&&(this.tutorHandAnimation.play(),this.scheduleOnce((function(){i.tutorHandAnimation.stop()})))),this.node.worldPosition!=this._previousPosition&&p(this.handle).to(.1,{worldPosition:this._previousPosition})},r.mouseClickMove=function(t){var i=this.handle.position,e=i.x,n=i.z,o=new c(t.getUILocation().x,t.getUILocation().y,n),a=this.hadleTransform.convertToNodeSpaceAR(o);a.x=e,a.y=m.clamp(a.y,this.minY,this.maxY),this._handleSpeed=(a.y-this.minY)/this._diapazon;var r=this.hadleTransform.convertToWorldSpaceAR(a);this.handle.setWorldPosition(r)},r.mouseClickEnd=function(t){this._previousPosition=this.handle.worldPosition.clone()},a(i,[{key:"handleSpeed",get:function(){return this._handleSpeed}}]),i}(f)).prototype,"minY",[y],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return-106}}),g=i(w.prototype,"maxY",[C],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return 106}}),z=i(w.prototype,"handle",[_],{configurable:!0,enumerable:!0,writable:!0,initializer:null}),A=i(w.prototype,"tutorHandAnimation",[T],{configurable:!0,enumerable:!0,writable:!0,initializer:null}),E=i(w.prototype,"hadleTransform",[H],{configurable:!0,enumerable:!0,writable:!0,initializer:null}),b=w))||b));r._RF.pop()}}}));

System.register("chunks:///_virtual/MachineComponent.ts",["./rollupPluginModLoBabelHelpers.js","cc","./GameEvent.ts","./FanComponent.ts","./HandleComponent.ts","./WheelComponent.ts"],(function(e){"use strict";var n,t,o,i,a,r,l,s,h,p,c,d,u,C,m;return{setters:[function(e){n=e.applyDecoratedDescriptor,t=e.inheritsLoose,o=e.initializerDefineProperty,i=e.assertThisInitialized},function(e){a=e.cclegacy,r=e._decorator,l=e.CCFloat,s=e.Collider,h=e.RigidBody,p=e.Vec3,c=e.Component},function(e){d=e.GameEvent},function(e){u=e.FanComponent},function(e){C=e.HandleComponent},function(e){m=e.WheelComponent}],execute:function(){var f,b,y,g,v,R,w,B,M;a._RF.push({},"606d1Y9A/RHAprVKHwKKMth","MachineComponent",void 0);var E=r.ccclass,F=r.property;e("MachineComponent",(f=E("MachineComponent"),b=F(C),y=F(l),g=F(s),f((w=n((R=function(e){function n(){for(var n,t=arguments.length,a=new Array(t),r=0;r<t;r++)a[r]=arguments[r];return n=e.call.apply(e,[this].concat(a))||this,o(n,"handleCpmponent",w,i(n)),o(n,"speed",B,i(n)),o(n,"bodyCollider",M,i(n)),n.wheels=[],n.partsRB=[],n.fan=void 0,n}t(n,e);var a=n.prototype;return a.start=function(){this.partsRB=this.node.getComponentsInChildren(h),this.partsRB.push(this.node.getComponent(h)),this.fan=this.node.getComponentInChildren(u),this.onDisableRB(),this.wheels=this.node.getComponentsInChildren(m),d.on("CRASH",this.onCrash,this),this.bodyCollider.on("onTriggerEnter",this.onCoinCollect,this)},a.update=function(e){var n=this,t=this.node.position.clone();t.x+=this.speed*this.handleCpmponent.handleSpeed*e,this.node.position=t,this.wheels.forEach((function(e){e.rotateWheel(n.handleCpmponent.handleSpeed)})),this.fan.rotate(this.handleCpmponent.handleSpeed)},a.onCrash=function(){this.partsRB.forEach((function(e){e.enabled=!0,e.useGravity=!0,e.linearFactor=new p(4*Math.random(),4*Math.random(),4*Math.random())})),this.handleCpmponent.node.active=!1},a.onDisableRB=function(){this.partsRB.forEach((function(e){e.name.includes("wheel")||(e.enabled=!1)}))},a.onCoinCollect=function(e){e.otherCollider.node.name.includes("Coin")&&(e.otherCollider.node.active=!1,d.emit("COIN_COLLECT"))},n}(c)).prototype,"handleCpmponent",[b],{configurable:!0,enumerable:!0,writable:!0,initializer:null}),B=n(R.prototype,"speed",[y],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return 25}}),M=n(R.prototype,"bodyCollider",[g],{configurable:!0,enumerable:!0,writable:!0,initializer:null}),v=R))||v));a._RF.pop()}}}));

System.register("chunks:///_virtual/main",["./CameraComponent.ts","./CoinComponent.ts","./FanComponent.ts","./HandleComponent.ts","./MachineComponent.ts","./RoadBlockComponent.ts","./TrapBlockComponent.ts","./DownloadComponent.ts","./FailWindowComponent.ts","./ScoreComponent.ts","./WheelComponent.ts","./GameEvent.ts","./GameEventName.ts","./t.ts","./URL.ts"],(function(){"use strict";return{setters:[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],execute:function(){}}}));

System.register("chunks:///_virtual/RoadBlockComponent.ts",["./rollupPluginModLoBabelHelpers.js","cc"],(function(o){"use strict";var t,n,e,i,r,c,l;return{setters:[function(o){t=o.inheritsLoose},function(o){n=o.cclegacy,e=o._decorator,i=o.Collider,r=o.RigidBody,c=o.ERigidBodyType,l=o.Component}],execute:function(){var s;n._RF.push({},"1c321OQ+qlOc55GZuaYpyg7","RoadBlockComponent",void 0);var d=e.ccclass,a=(e.property,e.requireComponent);o("RoadBlockComponent",d("RoadBlockComponent")(s=a(i)(s=a(r)(s=function(o){function n(){for(var t,n=arguments.length,e=new Array(n),i=0;i<n;i++)e[i]=arguments[i];return(t=o.call.apply(o,[this].concat(e))||this).collider=void 0,t.rb=void 0,t}t(n,o);var e=n.prototype;return e.start=function(){this.collider=this.node.getComponent(i),this.rb=this.node.getComponent(r),this.collider&&this.collider.on("onCollisionExit",this.collisionEnd,this)},e.collisionEnd=function(o){"wheel_back"==o.otherCollider.node.name&&(this.rb.type=c.DYNAMIC)},n}(l))||s)||s)||s);n._RF.pop()}}}));

System.register("chunks:///_virtual/ScoreComponent.ts",["./rollupPluginModLoBabelHelpers.js","cc","./GameEvent.ts"],(function(t){"use strict";var n,o,e,i,c,r;return{setters:[function(t){n=t.inheritsLoose},function(t){o=t.cclegacy,e=t._decorator,i=t.Label,c=t.Component},function(t){r=t.GameEvent}],execute:function(){var a;o._RF.push({},"8c51af8h1VDaZLyMCAjIf0C","ScoreComponent",void 0);var s=e.ccclass,u=(e.property,e.requireComponent);t("ScoreComponent",s("ScoreComponent")(a=u(i)(a=function(t){function o(){for(var n,o=arguments.length,e=new Array(o),i=0;i<o;i++)e[i]=arguments[i];return(n=t.call.apply(t,[this].concat(e))||this).coinText=void 0,n.coinQuantity=0,n}n(o,t);var e=o.prototype;return e.start=function(){this.coinText=this.node.getComponent(i),this.updateLabel(),r.on("COIN_COLLECT",this.onCollectCoin,this)},e.onCollectCoin=function(){this.coinQuantity++,this.updateLabel()},e.updateLabel=function(){this.coinText.string=this.coinQuantity.toString()},o}(c))||a)||a);o._RF.pop()}}}));

System.register("chunks:///_virtual/t.ts",["./rollupPluginModLoBabelHelpers.js","cc"],(function(t){"use strict";var o,n,e,r,i;return{setters:[function(t){o=t.inheritsLoose},function(t){n=t.cclegacy,e=t._decorator,r=t.Vec3,i=t.Component}],execute:function(){var s;n._RF.push({},"12f6eTwhN1OEp6mLXa6Mdez","t",void 0);var a=e.ccclass;e.property,t("t",a("t")(s=function(t){function n(){for(var o,n=arguments.length,e=new Array(n),i=0;i<n;i++)e[i]=arguments[i];return(o=t.call.apply(t,[this].concat(e))||this).startRotation=new r,o}o(n,t);var e=n.prototype;return e.start=function(){this.startRotation=new r,this.node.rotation.getEulerAngles(this.startRotation)},e.update=function(t){var o=this.node.getRotation();o.y,o.w;this.startRotation.y+=5,this.node.setRotationFromEuler(this.startRotation)},n}(i))||s);n._RF.pop()}}}));

System.register("chunks:///_virtual/TrapBlockComponent.ts",["./rollupPluginModLoBabelHelpers.js","cc","./GameEvent.ts"],(function(o){"use strict";var t,e,n,i,r,c,l,s;return{setters:[function(o){t=o.inheritsLoose},function(o){e=o.cclegacy,n=o._decorator,i=o.Collider,r=o.RigidBody,c=o.ERigidBodyType,l=o.Component},function(o){s=o.GameEvent}],execute:function(){var a;e._RF.push({},"ac8e9EYrNtGHIiLMH5F6QdO","TrapBlockComponent",void 0);var p=n.ccclass;n.property,o("TrapBlockComponent",p("TrapBlockComponent")(a=function(o){function e(){for(var t,e=arguments.length,n=new Array(e),i=0;i<e;i++)n[i]=arguments[i];return(t=o.call.apply(o,[this].concat(n))||this).collider=void 0,t.rb=void 0,t}t(e,o);var n=e.prototype;return n.start=function(){this.collider=this.node.getComponent(i),this.rb=this.node.getComponent(r),this.collider&&this.collider.on("onCollisionEnter",this.collisionStart,this)},n.collisionStart=function(o){"wheel_front"==o.otherCollider.node.name&&(this.rb.type=c.DYNAMIC,s.emit("CRASH"))},e}(l))||a);e._RF.pop()}}}));

System.register("chunks:///_virtual/URL.ts",["./rollupPluginModLoBabelHelpers.js","cc"],(function(t){"use strict";var e,r,c;return{setters:[function(t){e=t.createClass},function(t){r=t.cclegacy,c=t._decorator}],execute:function(){var u,n;r._RF.push({},"d0a7720n2RM/rTQaxPUamjl","URL",void 0);var o=c.ccclass;t("URL",o("URL")(((n=function(){function t(){}return e(t,null,[{key:"url",get:function(){return this._url}}]),t}())._url=encodeURI("https://play.google.com/store/apps/details?id=com.LuB.DeliveryConstruct&hl=ruw"),u=n))||u);r._RF.pop()}}}));

System.register("chunks:///_virtual/WheelComponent.ts",["./rollupPluginModLoBabelHelpers.js","cc"],(function(t){"use strict";var o,e,n,r,s;return{setters:[function(t){o=t.inheritsLoose},function(t){e=t.cclegacy,n=t._decorator,r=t.Vec3,s=t.Component}],execute:function(){var i;e._RF.push({},"30eb78kKl5Bv4STN+o8xF5p","WheelComponent",void 0);var a=n.ccclass;n.property,t("WheelComponent",a("WheelComponent")(i=function(t){function e(){for(var o,e=arguments.length,n=new Array(e),s=0;s<e;s++)n[s]=arguments[s];return(o=t.call.apply(t,[this].concat(n))||this).startRotation=new r,o}o(e,t);var n=e.prototype;return n.start=function(){this.startRotation=new r,this.node.rotation.getEulerAngles(this.startRotation)},n.rotateWheel=function(t){this.startRotation.y+=5*t,this.node.setRotationFromEuler(this.startRotation)},e}(s))||i);e._RF.pop()}}}));

(function(r) {
  r('virtual:///prerequisite-imports/main', 'chunks:///_virtual/main'); 
})(function(mid, cid) {
    System.register(mid, [cid], function (_export, _context) {
    return {
        setters: [function(_m) {
            var _exportObj = {};

            for (var _key in _m) {
              if (_key !== "default" && _key !== "__esModule") _exportObj[_key] = _m[_key];
            }
      
            _export(_exportObj);
        }],
        execute: function () { }
    };
    });
});
//# sourceMappingURL=index.js.map